apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-data-cloned
spec:
  storageClassName: zfs-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: example-data
    kind: PersistentVolumeClaim
    apiGroup: ""
